### ISSUE TITLE
brew docker install guidance on macOS doesn't install all needed docker components 

### ISSUE THREAD

**Issue by lknittig-panw** [hotpeppersec/Assassin#3]
on macos `brew docker install` will only install docker client.. not docker-compose and "desktop" which includes docker daemon running on unix socket docker.sock

related to directions from Quickstart for MAC
[https://github.com/hotpeppersec/Assassin/blob/master/docs/QUICKSTART_MAC.md](url)

suggest user as pre-req install docker-desktop for mac from : 
https://www.docker.com/products/docker-desktop

**Comment by hotpeppersec** [comment]
If you have a fix and want to add it, please feel free to push a change!

**Comment by lknittig-panw** [comment]
udpated quickstart.MD with docker desktop and API key config guidances
